# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            tnesland.me
tagline:          Software Developer + Data Wrangler
url:              http://tnesland.me
shorturl:	  tnesland.me
paginate:         5
baseurl:          /
author:
  name:           Travis Nesland
  url:            http://tnesland.me
  email:          tnesland@gmail.com

# Navigation
pages_list:
  Home: '/'
  Archive: '/archive'

# Custom vars
version:          1.0.0
github:
  repo:           https://github.com/tnez/tnez.github.io

